# For more information on GitHub Actions, refer to https://github.com/features/actions
name: LeetCode

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    # Execute .NET unit tests in the solution
    - name: Execute unit tests
      run: dotnet test src/csharp/Challenges.slnx
